version: '3.8'
services:
  frontend:
    image: euegenechoi/aibe1-finalproject-todayscommit_fe-client:latest
    ports:
      - "5173:5173"
    env_file:
      - .env.production

  backend:
    image: euegenechoi/aibe1-finalproject-todayscommit_fe-server:latest
    ports:
      - "3000:3000"
    env_file:
      - .env.production
