version: '3.8'

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/${REPO_NAME_LOWER}-server:latest
    ports:
      - "3000:3000"
    env_file:
      - .env.production

  frontend:
    image: ${DOCKERHUB_USERNAME}/${REPO_NAME_LOWER}-client:latest
    ports:
      - "5173:5173"
    env_file:
      - .env.production
